app/views/CharitiesCommunityAmateurSportsView.scala.html
app/views/ConstructionIndustrySchemeView.scala.html
app/views/CorporationTaxEnquiriesView.scala.html
app/views/EmployingExpatriateEmployeesView.scala.html
app/views/EmploymentRelatedSecuritiesView.scala.html
app/views/NonUkResidentEmployeesView.scala.html
app/views/NonUkResidentLandlordsView.scala.html
app/views/PaymentProblemsView.scala.html
conf/messages
test/views/html/pages/CharitiesCommunityAmateurSportsViewSpec.scala
test/views/html/pages/ConstructionIndustrySchemeViewSpec.scala
test/views/html/pages/CorporationTaxEnquiriesViewSpec.scala
test/views/html/pages/EmployingExpatriateEmployeesViewSpec.scala
test/views/html/pages/EmploymentRelatedSecuritiesViewSpec.scala
test/views/html/pages/NonUkResidentEmployeesViewSpec.scala
test/views/html/pages/NonUkResidentLandlordsViewSpec.scala
test/views/html/pages/PaymentProblemsViewSpec.scala

Remove 'They will not be able to transfer you to another webchat team'

[DEP-255] - Remove content 

---

public/javascripts/custom.js

Set tabindex of webchat iFrame = 2
Set tabindex of main page footer = 3

[DEP-227] - Apply tabindex order to chat iFrame and Footer

---

app/views/MainTemplate.scala.html
public/javascripts/custom.js

Re-position nuance script in attempt to inject before footer
Revert tabIndex applied within custom script.js

[DEP-227] - Re-position nuance script

---

app/views/SelfEmploymentIncomeSupportView.scala.html
conf/messages
test/views/html/pages/ChatViewBehaviours.scala
test/views/html/pages/ChildBenefitViewSpec.scala
test/views/html/pages/ConstructionIndustrySchemeViewSpec.scala
test/views/html/pages/CorporationTaxEnquiriesViewSpec.scala
test/views/html/pages/CustomerEnquiriesViewSpec.scala
test/views/html/pages/EmployerEnquiriesViewSpec.scala
test/views/html/pages/EmploymentRelatedSecuritiesViewSpec.scala
test/views/html/pages/IncomeTaxEnquiriesViewSpec.scala
test/views/html/pages/InheritanceTaxViewSpec.scala
test/views/html/pages/JobRetentionSchemeViewSpec.scala
test/views/html/pages/NationalInsuranceNumbersViewSpec.scala
test/views/html/pages/NonUkResidentEmployeesViewSpec.scala
test/views/html/pages/NonUkResidentLandlordsViewSpec.scala
test/views/html/pages/OnlineServiceHelpdeckViewSpec.scala
test/views/html/pages/ProbateViewSpec.scala
test/views/html/pages/SelfAssessmentViewSpec.scala
test/views/html/pages/SelfEmploymentIncomeSupportViewSpec.scala
test/views/html/pages/TaxCreditsViewSpec.scala
test/views/html/pages/VatEnquirirsViewSpec.scala
test/views/html/pages/VatOnlineServioceHelpdeskViewSpec.scala
test/views/html/pages/VatRegistrationViewSpec.scala

Refactor view behaviour and update unit tests

[DEP-363] - Update SEISS opening hours. 

---

app/controllers/IvrController.scala
conf/app.routes
test/controllers/IvrControllerSpec.scala

* Removing routes then we hit a 404
* Commenting out method in IVR controller as it was failing compilation since routes are not there anymore.

EAT-OUT-TO-HELP-OUT-REMOVAL

---

app/views/IdTestView.scala.html
app/views/NuanceFullPageCUIView.scala.html
conf/testOnlyDoNotUseInAppConf.routes
test/views/html/pages/NuanceFullPageUCIViewSpec.scala

DEP-1218: Change content and styling on Nuance test page per their request

---

app/views/NuanceFullPageCUIView.scala.html
test/controllers/testOnlyDoNotUseInAppConf/NuanceFullPageCUIControllerSpec.scala
test/views/html/pages/NuanceFullPageUCIViewSpec.scala

This is a complete hack job due to short notice.

Change Nuance test page per Dug's request. 

---

app/assets/javascripts/cuiChatListener.js

1) Wait for longer time before showing error.
2) If chat engages after showing error, hide error.
3) Remove "group" styling for error, since it's not a validation error.

DEP-1344: Tweaks for CUI loading animation

---

conf/local.conf
run_local.sh

This will be added to service manager, once built.

Add support for running in "local" mode, where pages can be sourced.

---

app/views/includes/cuiGenericSidebar.scala.html
conf/messages
test/views/html/pages/includes/cuiGenericSidebarSpec.scala

[DEP-2214][PR]:Tax Credits Webchat updated opening hours (for 02/10)

[DEP-2214][PR]:Tax Credits Webchat updated opening hours (for 02/10)

---

app/assets/javascripts/ci_api/ContainerHtml.js
app/assets/javascripts/ci_api/Transcript.js
app/assets/stylesheets/ci_api/chat-ui-embedded.scss
app/assets/stylesheets/ci_api/chat-ui-popup.scss
conf/application.conf

DEP-2162: Implement 'Skip Links' in chat window Embedded & Pop up (related to R8)

DEP-2162: Implement 'Skip Links' in chat window Embedded & Pop up (related to R8)

---

app/assets/stylesheets/ci_api/chat-ui-popup.scss

DEP-2381 : fixed link styles in chat and on focus

DEP-2381 : fixed link styles in chat and on focus

---

app/assets/stylesheets/ci_api/chat-ui-embedded.scss
app/assets/stylesheets/ci_api/chat-ui-popup.scss
app/assets/stylesheets/custom.css

DEP-2307: Fixed extra padding for mobile

DEP-2307: Fixed extra padding for mobile

---

app/controllers/CuiController/CuiController.scala
app/controllers/IvrController.scala
app/controllers/VirtualAssistantController.scala
app/controllers/WebchatController.scala
app/views/CUIViews/AskHmrcOnlineCUIView.scala.html
project/AppDependencies.scala
project/plugins.sbt
test/controllers/CuiController/CuiControllerSpec.scala
test/controllers/VirtualAssistantControllerSpec.scala
test/controllers/WebchatControllerSpec.scala

1. Library and Plugin Upgrades
2. Updated fixed error while upgrading sbt plugin to 2.8.8 along with test

[DEP-2275][PR]:Library and Plugin Upgrades

---

app/assets/javascripts/ci_api/ChatContainer.js
app/assets/javascripts/ci_api/ChatController.js
app/assets/javascripts/ci_api/EndChatPopup.js
app/assets/javascripts/ci_api/PostChatSurvey.js
app/assets/javascripts/ci_api/PostPCSPage.js
app/assets/stylesheets/ci_api/chat-ui-embedded.scss
app/assets/stylesheets/ci_api/chat-ui-popup.scss

DEP-2304, DEP-2305 : Fixed focus issue for end chat

---

project/AppDependencies.scala

- []  I've included appropriate tests with any code I've added (Unit, Integration, Acceptance etc.)

Update Chat Library

---

app/assets/javascripts/ci_api/controllers/CommonChatController.js
app/assets/javascripts/ci_api/services/Transcript.js
app/assets/javascripts/ci_api/utils/ChatContainer.js
app/assets/javascripts/ci_api/views/embedded/EmbeddedContainerHtml.js
test/javascripts/ci_api/services/Transcript.spec.js

DEP-2386 : Fix main page scroll issues on Embedded following Implementation of 'Skip Links'

---

app/assets/javascripts/ci_api/controllers/CommonChatController.js
app/assets/javascripts/ci_api/services/Transcript.js
app/assets/javascripts/ci_api/views/popup/PopupContainerHtml.js
app/assets/stylesheets/ci_api/chat-ui-embedded.scss
app/assets/stylesheets/ci_api/chat-ui-popup.scss
app/views/templates/GovukWrapper.scala.html
test/javascripts/ci_api/controllers/ProactiveChatController.spec.js
test/javascripts/ci_api/services/Transcript.spec.js

DEP-2102: FIxed tabbing order for popup

---

app/config/AppConfig.scala
app/views/includes/cuiCJRSSidebar.scala.html
conf/application.conf
conf/messages
test/views/html/pages/includes/cuiCJRSSidebarSpec.scala

Added CJRS sidebar and toggle

---

conf/messages
test/views/html/pages/includes/cuiSASidebarSpec.scala
test/views/html/pages/templates/GovukWrapperCUISpec.scala

DEP-2462: Changed content on DAv2 SA page

---

.github/PULL_REQUEST_TEMPLATE.md

DEP-2384 : Updated the PR checklist

---

app/views/CUIHMRCSkinViews/TaxCreditsCUIView.scala.html
test/views/html/pages/CUIHMRCSkinViews/TaxCreditsCUIViewSpec.scala

DEP-2511 : Added DAv3 embedded css to tax credits page

---

app/assets/stylesheets/ci_api/chat-ui-embedded.scss

removed unneeded css

---

app/views/includes/christmasNewYearOpenTimes.scala.html
app/views/webchat/AdditionalNeedsHelpView.scala.html
app/views/webchat/C19EmployerEnquiriesView.scala.html
app/views/webchat/ChildBenefitView.scala.html
app/views/webchat/ConstructionIndustrySchemeView.scala.html
app/views/webchat/CorporationTaxEnquiriesView.scala.html
app/views/webchat/CustomsEnquiriesView.scala.html
app/views/webchat/EmployerEnquiriesView.scala.html
app/views/webchat/EmploymentRelatedSecuritiesView.scala.html
app/views/webchat/ExciseEnquiriesView.scala.html
app/views/webchat/IncomeTaxEnquiriesView.scala.html
app/views/webchat/Ir35EnquiriesView.scala.html
app/views/webchat/JobRetentionSchemeView.scala.html
app/views/webchat/NationalInsuranceNumbersView.scala.html
app/views/webchat/NonUkResidentLandlordsView.scala.html
app/views/webchat/OnlineServiceHelpdeskView.scala.html
app/views/webchat/PaymentProblemsView.scala.html
app/views/webchat/PersonalTransportUnitEnquiriesView.scala.html
app/views/webchat/SelfAssessmentView.scala.html
app/views/webchat/SelfEmploymentIncomeSupportView.scala.html
app/views/webchat/VatEnquiriesView.scala.html
app/views/webchat/VatOnlineServicesHelpdeskView.scala.html
app/views/webchat/VatRegistrationView.scala.html
conf/messages
test/views/html/pages/includes/christmasNewYearOpenTimesSpec.scala
test/views/html/pages/webchat/CustomsEnquiriesViewSpec.scala

DEP-2501: Added most of the open hours changes we know of

---

app/views/ci_api/CiApiDemoViewEmbedded.scala.html

Change CIAPI Container div

---

app/views/ci_api/CiApiDemoViewPopup.scala.html

DEP-2436b : Remove unneeded div from demo popup

---

app/assets/stylesheets/custom.css
app/config/AppConfig.scala
app/views/components/DepHeader.scala.html
app/views/helpers/DepStandardHeader.scala.html
app/views/templates/GovukWrapper.scala.html
app/views/templates/GovukWrapperCUI.scala.html

DEP-2521 : Create and add custom UR banner to DAv1 and DAv2 pages

---

app/controllers/WebchatController.scala
test/controllers/WebchatControllerSpec.scala

DEP-2546: Committed the Webchat Closure Update code

---

app/assets/stylesheets/custom.css

DEP-2521 : Removed padding on no thanks link and re positioned

---

app/assets/stylesheets/custom.css
app/views/components/DepHeader.scala.html

Change UR Banner title (again)

---

app/controllers/WebchatController.scala
test/controllers/WebchatControllerSpec.scala

Below is the link for AT PR:
https://github.com/hmrc/digital-engagement-platform-journey-tests/pull/75

DEP-2596: Committed the Webchat Closure Update code

---

app/views/components/DepHeader.scala.html

Remove extra quotation mark

---

app/controllers/IvrController.scala
app/controllers/WebchatController.scala
test/controllers/IvrControllerSpec.scala
test/controllers/WebchatControllerSpec.scala

DEP- 2678 Commited the Redirect ALL Tax Credit URLS to DAv2

---

app/config/AppConfig.scala
app/views/webchat/ServiceUnavailableView.scala.html
conf/messages
test/views/html/pages/webchat/ServiceUnavailableViewSpec.scala

DEP- 2643 Commited the code for new content on shutter page

---

app/controllers/CuiController/CuiController.scala
conf/app.routes
test/controllers/CuiController/CuiControllerSpec.scala

DEP- 2465 Remove old variant B route for DAv2 JRS page

---

conf/messages
test/views/html/pages/CUIViews/OnlineServicesHelpdeskCUIViewSpec.scala
test/views/html/pages/includes/cuiOSHSidebarSpec.scala

DEP-2813 Updated the OSH DAv2 Header and the sidebar content

---

README.md
app/controllers/WebchatController.scala
test/controllers/WebchatControllerSpec.scala

DEP-2951: un-shutter IR35 webchat page

---

README.md
app/config/AppConfig.scala
app/controllers/WebchatController.scala
conf/application.conf
test/controllers/WebchatControllerSpec.scala

DEP-2951 : Added shutter feature flag to IR35 Enquiries

---

app/config/AppConfig.scala
app/controllers/CuiController/CuiController.scala
app/controllers/WebchatController.scala
app/views/CUIViews/EmployerEnquiriesCUIView.scala.html
app/views/includes/cuiEmployerEnquiriesSidebar.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CuiController/CuiControllerSpec.scala
test/controllers/WebchatControllerSpec.scala
test/views/html/pages/CUIViews/EmployerEnquiriesCUIViewSpec.scala
test/views/html/pages/includes/sidebarEmployerEnquiriesCUISpec.scala

DEP-3020: Add redirect to EHL DAv1 to DAv2 when EHL flag true

---

app/config/AppConfig.scala
app/views/templates/GovukWrapperCUIv3.scala.html
app/views/templates/MainTemplateCUIv3.scala.html

DEP-3023 : Create new govukwrapper for dav3

---

app/assets/javascripts/cuiChatListener.js
test/javascripts/cuiChatListener.spec.js

DEP :  Fix load timer and remove error message when not needed

---

app/views/templates/GovukWrapper.scala.html

[DEP-3052][PR]:Removal of HMRC Logo banner

---

app/assets/javascripts/cuiChatListener.js
test/javascripts/cuiChatListener.spec.js

DEP-2807: added aria live to tech error

---

app/controllers/StampDutyController.scala
app/controllers/WebchatController.scala
build.sbt
project/AppDependencies.scala
project/build.properties
project/plugins.sbt
test/controllers/WebchatControllerSpec.scala

Updating dependencies and some tidying

---

app/assets/stylesheets/custom.css
app/views/templates/GovukWrapperCUI.scala.html

DEP-3096a Fix height issue

---

app/assets/stylesheets/custom.css
app/views/CUIHMRCSkinViews/TaxCreditsCUIView.scala.html
app/views/CUIViews/EmployerEnquiriesCUIView.scala.html
app/views/CUIViews/JobRetentionSchemeHelpView.scala.html
app/views/CUIViews/NuanceFullPageCUIView.scala.html
app/views/CUIViews/OnlineServicesHelpdeskCUIView.scala.html
app/views/CUIViews/SelfAssessmentCUIView.scala.html
app/views/ci_api/CiApiDemoViewEmbedded.scala.html
test/javascripts/cuiChatListener.spec.js

DEP-3096c - overlay fix

---

app/assets/stylesheets/custom.css

Needs matching PR from https://github.com/hmrc/digital-engagement-platform-skin/pull/94

adam-popup - update height to match DAv2

---

conf/messages

Link to AT PR : https://github.com/hmrc/digital-engagement-platform-journey-tests/pull/97

[DEP-3514][PR]:Changed content on shutter page

---

app/config/AppConfig.scala
app/controllers/CuiController/CuiController.scala
app/controllers/WebchatController.scala
app/views/CUIViews/ChildBenefitCUIView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CuiController/CuiControllerSpec.scala
test/views/html/pages/CUIViews/ChildBenefitCUIViewSpec.scala

- Just a draft PR with New CUI page for CHB
- Also covers redirect of webcaht
- unit test - work in progress

[DEP-3486][PR]:New CHB DAv2 page and redirect

---

app/assets/javascripts/cuiChatListener.js
test/javascripts/cuiChatListener.spec.js

DEP-3547 : Increase time before showing nuance loaded error message

---

conf/application-json-logger.xml
conf/application.conf
conf/local.conf
project/AppDependencies.scala
project/plugins.sbt

Update with new digital-engagement-platform-chat version once this PR is merged: 
https://github.com/hmrc/digital-engagement-platform-chat/pull/34

DEP-3452 update dependencies

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/VatOnlineCuiView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/VatOnlineCuiViewSpec.scala

DEP-3646 Added new VAT Online view.

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/CorporationTaxCuiView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/CorporationTaxCuiViewSpec.scala

DEP-3711 corporation tax page added

---

conf/app.routes

DEP-3711 corporation tax url change

---

app/controllers/WebchatController.scala
test/controllers/WebchatControllerSpec.scala

DEP-3599 customs webchat redirect to DAv2

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/TradeTariffCUIView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/TradeTariffCuiViewSpec.scala

DEP-3951 add trade tariff page

---

app/audit/AuditHelper.scala
app/controllers/CiapiController/CiapiController.scala
app/models/AuditModel.scala
app/models/DAv3AuditModel.scala
project/AppDependencies.scala
test/controllers/CiapiController/CiapiControllerSpec.scala
test/mocks/MockAuditService.scala

DEP-3813 Added audit events to controller load events.

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/DebtManagementCUIView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/DebtManagementCuiViewSpec.scala

DEP-4143 Create page for Debt Management 

---

conf/messages
package-lock.json
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/DebtManagementCuiViewSpec.scala

DEP-4143 payment problems heading and title update

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/SelfAssessmentIVRView.scala.html
conf/application.conf
conf/ivr.routes
conf/messages
conf/prod.routes
package-lock.json
test/controllers/IvrControllerSpec/IvrControllerSpec.scala
test/views/html/pages/IVR/SelfAssessmentIVRViewSpec.scala
test/views/html/pages/helpers/ChatViewBehaviours.scala
test/views/html/pages/webchat/ConstructionIndustrySchemeViewSpec.scala
test/views/html/pages/webchat/Ir35EnquiriesViewSpec.scala
test/views/html/pages/webchat/NationalClearanceHubViewSpec.scala
test/views/html/pages/webchat/OnlineServiceHelpdeskViewSpec.scala
test/views/html/pages/webchat/PersonalTransportUnitEnquiriesViewSpec.scala

DEP-4267: Add IVR SA page

---

conf/app.routes

DEP-4165 remove csrf check for monitoring tags.

---

app/config/AppConfig.scala
app/views/IVR/SelfAssessmentIVRView.scala.html
build.sbt
conf/messages
project/plugins.sbt

DEP-4403: added security text for ivr sa page

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/NationalInsuranceCUIView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/NationalInsuranceCUIViewSpec.scala

DEP-3497: Created CIAPI National Insurance page

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/PAYECUIView.scala.html
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala
test/views/html/pages/CIAPIViews/PAYECUIViewSpec.scala

DEP 4790 PAYE DAV3 page & tests

---

app/config/AppConfig.scala
conf/messages

Dep 4475 verified

---

app/assets/stylesheets/custom.css
app/views/templates/GovukWrapper.scala.html
app/views/templates/GovukWrapperCUI.scala.html
conf/messages
package-lock.json

DEP-5263 added notification banner

---

app/views/testOnly/NuanceFile.scala.html
conf/application.conf
package-lock.json

DEP-5202 update URLs for nuance updates

---

app/views/CIAPIViews/DebtManagementCUIView.scala.html
package-lock.json
test/views/html/pages/CIAPIViews/DebtManagementCuiViewSpec.scala

DEP-5601 Removed computer message from webchat for debt management.

---

app/assets/stylesheets/custom.css
app/views/templates/GovukWrapper.scala.html
app/views/templates/GovukWrapperCUI.scala.html
conf/messages
package-lock.json

added notification banner

---

app/assets/javascripts/custom.js
conf/messages

added in new banner message and timings

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/NationalInsuranceIVRView.scala.html
conf/application.conf
conf/ivr.routes
conf/messages
test/controllers/IvrControllerSpec/IvrControllerSpec.scala

created new page for NI

---

app/views/IVR/NationalInsuranceIVRView.scala.html

removed opening times

---

app/views/IVR/NationalInsuranceIVRView.scala.html
conf/messages

Dep 5877 opening times

---

app/controllers/testOnlyDoNotUseInAppConf/TestController.scala
app/views/testOnly/PersistChatPageOneViewPopup.scala.html
app/views/testOnly/PersistChatPageTwoViewPopup.scala.html
conf/testOnlyDoNotUseInAppConf.routes
test/controllers/testOnlyDoNotUseInAppConf/TestControllerSpec.scala
test/views/html/pages/testOnly/persistChatPageOneViewPopupSpec.scala
test/views/html/pages/testOnly/persistChatPageTwoViewPopupSpec.scala

DEP-5896 persist chat pages created

---

conf/app.routes

DEP-5904 new SA filing route

---

app/controllers/testOnlyDoNotUseInAppConf/TestController.scala
app/views/testOnly/C2cViewPopup.scala.html
conf/testOnlyDoNotUseInAppConf.routes
test/controllers/testOnlyDoNotUseInAppConf/TestControllerSpec.scala
test/views/html/pages/testOnly/c2cViewPopupSpec.scala

DEP-2636 c2c test page

---

app/assets/javascripts/custom.js
conf/messages

Dep 5950 change

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/DebtManagementIVRView.scala.html
conf/application.conf
conf/ivr.routes
conf/messages
project/plugins.sbt
test/controllers/IvrControllerSpec/IvrControllerSpec.scala
test/views/html/pages/IVR/DebtManagementIVRViewSpec.scala
test/views/html/pages/IVR/NationalInsuranceIVRViewSpec.scala

New debt management page

---

app/views/testOnly/CiApiDemoViewPopup.scala.html
test/views/html/pages/testOnly/ciApiDemoViewPopupSpec.scala

DEP-accessibility popup page title update

---

app/config/AppConfig.scala

Dep list page fix

---

app/assets/javascripts/custom.js
conf/messages

banner message

---

conf/application.conf

DEP-Policy-Removal-Test.

---

app/views/templates/GovukWrapper.scala.html
app/views/templates/GovukWrapperCUI.scala.html
app/views/templates/MainTemplate.scala.html
app/views/templates/MainTemplateCUI.scala.html
app/views/testOnly/C2cViewPopup.scala.html
app/views/testOnly/CiApiDemoViewPopup.scala.html
app/views/testOnly/CiApiDemoViewProactivePopup.scala.html
app/views/testOnly/NuanceFile.scala.html
app/views/testOnly/PersistChatPageOneViewPopup.scala.html
app/views/testOnly/PersistChatPageTwoViewPopup.scala.html
conf/application.conf
project/AppDependencies.scala

DEP-nonce-change Altered Nonce Format to simplify generation.

---

project/AppDependencies.scala

DEP-6102 chat dependency upgrade

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala

added help to save page

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala

new adl page

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/ConstructionIndustrySchemeIVRView.scala.html
conf/application.conf
conf/ivr.routes
conf/messages
project/plugins.sbt
test/controllers/IvrControllerSpec/IvrControllerSpec.scala
test/views/html/pages/IVR/ConstructionIndustrySchemeIVRViewSpec.scala

IVR for CIS

---

app/controllers/IvrController/IvrController.scala
package-lock.json

DEP-6214-2 refactor

---

app/assets/javascripts/custom.js
package-lock.json

Hidden the back link when there is not history.

---

package-lock.json
project/AppDependencies.scala

DEP-6107 chat dependency

---

app/controllers/WebchatController.scala
conf/app.routes
test/controllers/WebchatControllerSpec.scala

removed redirect for CIS

---

conf/messages

changed title

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
conf/app.routes
conf/application.conf
package-lock.json
test/controllers/CiapiController/CiapiControllerSpec.scala

DEP-6234 Add trusts DaV3 page.

---

conf/messages

DEP-6407 added content for concierge page for trusts.

---

app/controllers/CiapiController/CiapiController.scala
conf/logback.xml
project/build.properties
project/plugins.sbt

removed banner from pages

---

app/assets/javascripts/custom.js
app/controllers/CiapiController/CiapiController.scala
conf/messages

DEP-6454 added banner to child benefit page

---

app/views/templates/MainTemplateCUI.scala.html
app/views/testOnly/C2cViewPopup.scala.html
app/views/testOnly/CiApiDemoViewPopup.scala.html
app/views/testOnly/CiApiDemoViewProactivePopup.scala.html
app/views/testOnly/PersistChatPageOneViewPopup.scala.html
app/views/testOnly/PersistChatPageTwoViewPopup.scala.html
package-lock.json

removed jquery scripts

---

app/assets/javascripts/custom.js
app/assets/stylesheets/_typography.scss
app/assets/stylesheets/main.scss
app/views/templates/GovukWrapper.scala.html
app/views/templates/GovukWrapperCUI.scala.html
app/views/templates/MainTemplate.scala.html
app/views/testOnly/C2cViewPopup.scala.html
app/views/testOnly/CiApiDemoViewPopup.scala.html
app/views/testOnly/CiApiDemoViewProactivePopup.scala.html
app/views/testOnly/PersistChatPageOneViewPopup.scala.html
app/views/testOnly/PersistChatPageTwoViewPopup.scala.html
package-lock.json

Dep pcs fix

---

app/config/AppConfig.scala
conf/application.conf
test/controllers/CiapiController/CiapiControllerSpec.scala

DEP-6489 - Hidden the support for tax agents links on the concierge page.

---

app/controllers/testOnlyDoNotUseInAppConf/TestController.scala
app/views/testOnly/C2cFixedViewPopup.scala.html
conf/testOnlyDoNotUseInAppConf.routes
test/controllers/testOnlyDoNotUseInAppConf/TestControllerSpec.scala
test/views/html/pages/testOnly/c2cFixedViewPopupSpec.scala

DEP-6503 fixed C2C test page

---

app/views/templates/GovukWrapper.scala.html

changed tabbing order on our frontend

---

app/assets/javascripts/custom.js

test for back link

---

app/assets/javascripts/custom.js

Dep 6609 fix

---

app/views/testOnly/CiApiDemoViewPopup.scala.html
test/views/html/pages/testOnly/ciApiDemoViewPopupSpec.scala

changed H1

---

app/config/AppConfig.scala
app/views/webchat/dav4/DAv4NationalClearanceHubView.scala.html
conf/application.conf
test/controllers/CiapiController/CiapiControllerSpec.scala

DEP-6690 Reinstated the ADL DA.

---

app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/TradeTariffCUIView.scala.html
app/views/includes/tradeTariffSidebar.scala.html
conf/messages
package-lock.json
test/controllers/CiapiController/CiapiControllerSpec.scala

DEP-6672: Updated the trade tariff page to reflect the opening times.

---

conf/app.routes
project/plugins.sbt

Adding self-assessment-cessation page 

---

app/views/IVR/ConstructionIndustrySchemeIVRView.scala.html
app/views/IVR/DebtManagementIVRView.scala.html
app/views/IVR/EmployerHelplineIVRView.scala.html
app/views/IVR/NationalInsuranceIVRView.scala.html
app/views/IVR/SelfAssessmentIVRView.scala.html
app/views/webchat/AdditionalNeedsHelpView.scala.html
app/views/webchat/PersonalTransportUnitEnquiriesView.scala.html
test/views/html/pages/webchat/AdditionalNeedsHelpViewSpec.scala
test/views/html/pages/webchat/PersonalTransportUnitEnquiriesViewSpec.scala

Adding Christmas Opening hours to live webchats pages

---

app/assets/javascripts/custom.js
app/controllers/CiapiController/CiapiController.scala
conf/messages

individual banner for tax credits

---

app/assets/javascripts/custom.js
app/controllers/CiapiController/CiapiController.scala
conf/messages

Dep 6854 fix

---

app/assets/javascripts/custom.js
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/AskHMRCOnlineCIAPIView.scala.html
app/views/templates/GovukWrapper.scala.html
app/views/templates/GovukWrapperCUI.scala.html
app/views/templates/MainTemplate.scala.html
app/views/templates/MainTemplateCUI.scala.html
conf/messages

Feat: Added a second timer for the OSH banner and refactored the code so we have displayBannerTC instead of displayBanner.

---

app/assets/stylesheets/custom.css
app/views/includes/testSidebar.scala.html
app/views/includes/tradeTariffSidebar.scala.html
conf/messages
test/views/html/pages/CIAPIViews/TradeTariffsCUIViewSpec.scala
test/views/html/pages/includes/testSidebarSpec.scala
test/views/html/pages/includes/tradeTariffsSidebarSpec.scala

DEP-6874: Content: Updated the text on the trade tariffs sidebar.

---

app/assets/javascripts/cuiChatListener.js

Adding null checks to the elements to remove console errors

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/dav4/DAv4SelfAssessmentIVRView.scala.html
conf/application.conf
test/controllers/IvrControllerSpec/IvrControllerSpec.scala
test/views/html/pages/IVR/ConstructionIndustrySchemeIVRViewSpec.scala
test/views/html/pages/IVR/DebtManagementIVRViewSpec.scala
test/views/html/pages/IVR/EmployerHelplineIVRViewSpec.scala
test/views/html/pages/IVR/NationalInsuranceIVRViewSpec.scala
test/views/html/pages/IVR/SelfAssessmentIVRViewSpec.scala
test/views/html/pages/IVR/dav4/DAv4SelfAssessmentIVRViewSpec.scala
test/views/html/pages/helpers/ChatViewBehaviours.scala
test/views/html/pages/webchat/AdditionalNeedsHelpViewSpec.scala
test/views/html/pages/webchat/NationalClearanceHubViewSpec.scala
test/views/html/pages/webchat/PersonalTransportUnitEnquiriesViewSpec.scala
test/views/html/pages/webchat/dav4/DAv4AdditionalNeedsHelpViewSpec.scala
test/views/html/pages/webchat/dav4/DAv4DebtManagementViewSpec.scala
test/views/html/pages/webchat/dav4/DAv4NationalClearanceHubViewSpec.scala
test/views/html/pages/webchat/dav4/DAv4PersonalTransportUnitEnquiriesViewSpec.scala

Feature: Created DAv4 IVR SA page with unit tests.

---

app/config/AppConfig.scala
app/controllers/CiapiController/CiapiController.scala
conf/app.routes
conf/application.conf
conf/messages
test/controllers/CiapiController/CiapiControllerSpec.scala

DEP-6868: New webpage and DAv3 created for Childcare service.

---

conf/messages

DEP-7039: Content: Changed Valued Added Tax to Value Added Tax.

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/dav4/DAv4DebtManagementIVRView.scala.html
conf/application.conf
test/controllers/IvrControllerSpec/IvrControllerSpec.scala
test/views/html/pages/IVR/dav4/DAv4DebtManagementIVRViewSpec.scala

Created new DM IVR page.

---

app/config/AppConfig.scala
app/controllers/IvrController/IvrController.scala
app/views/IVR/dav4/DAv4NationalInsuranceIVRView.scala.html
conf/application.conf
test/controllers/IvrControllerSpec/IvrControllerSpec.scala
test/views/html/pages/IVR/dav4/DAv4NationalInsuranceIVRViewSpec.scala

added NI IVR DAv4

---

app/views/webchat/dav4/DAv4PAYESAResolutionsView.scala.html
test/views/html/pages/webchat/dav4/DAv4PAYESAResolutionsViewSpec.scala

DEP-6910: Changed the opening times for PAYE SA Resolutions page and unit test.

---

app/views/webchat/dav4/DAv4PAYESAResolutionsView.scala.html
test/views/html/pages/webchat/dav4/DAv4PAYESAResolutionsViewSpec.scala

DEP-6910: Updated the times of PAYESAR to 9am to 4pm.

---

app/assets/javascripts/custom.js
app/controllers/CiapiController/CiapiController.scala
app/views/CIAPIViews/AskHMRCOnlineCIAPIView.scala.html
app/views/templates/GovukWrapperCUI.scala.html
app/views/templates/MainTemplateCUI.scala.html
conf/messages

two banners created

---

app/config/AppConfig.scala
test/controllers/AccessibilityStatementControllerSpec.scala

changed frontend accessibility link

---

app/assets/javascripts/waitForCIAPIFixedChanges.js

DEP-7076: Added functionality for the page title and error message to swap on the DAv4.
